fix: Paths.
Ajdjusts.

diff --git a/resources/hooks/git/post-receive b/resources/hooks/git/post-receive
--- a/resources/hooks/git/post-receive
+++ b/resources/hooks/git/post-receive
@@ -9,9 +9,9 @@ set_vars "" "" "" "" > /dev/null
 # - 2. The Premature Multi-Branch Deletion Bug
 
 SAFE_VAR_REGEX="^[a-zA-Z_][a-zA-Z0-9_]*=[a-zA-Z0-9_\.\/\-]+$"
-ALLOWED_VARS=("FORCE_REINSTALL_VENV" "TARGET_ENV" "FORGE_DEBUG" "FORGE_DRY_RUN")
+ALLOWED_VARS=("FORCE_REINSTALL_VENV" "FORCE_REINSTALL_DOCUMENT_ROOT" "TARGET_ENV" "FORGE_DEBUG" "FORGE_DRY_RUN")
 extract_vars() {
-    # Given a content line, extract the correct variable. Can be re-used with git option in push like `clear; date; [[ -z "$POINTER" ]] && POINTER="HEAD" || POINTER=""; git push deployment "$POINTER":refs/triggers/deploy --force -o FORCE_REINSTALL_VENV=0 -o TARGET_ENV=nami -o bla=blargh -o lala="lele" -o lili -o DARTH=VADER`
+    # Given a content line, extract the correct variable. Can be re-used with git option in push like `clear; date; [[ -z "$POINTER" ]] && POINTER="HEAD" || POINTER=""; git push deployment "$POINTER":refs/triggers/deploy --force -o FORCE_REINSTALL_DOCUMENT_ROOT=1 -o FORCE_REINSTALL_VENV=0 -o TARGET_ENV=nami -o FORGE_DRY_RUN=0 -o FORGE_DEBUG=1 -o bla=blargh -o lala="lele" -o lili -o DARTH=VADER`
     # Also can be re-used with git commit message body
     # [MANDATORY] $1 CONTENT        :: The line/value itself that will be parsed
     # [OPTIONAL]  $2 SILENT_DISCARD :: To silent the output messages
@@ -40,6 +40,14 @@ extract_vars() {
                         [[ "$SILENT_DISCARD" == "1" ]] && return 0 || echo "✅ Set the value for FORCE_REINSTALL_VENV as $FORCE_REINSTALL_VENV"
                     else
                         [[ "$SILENT_DISCARD" == "1" ]] && return 0 || echo "⚠️ Invalid value for FORCE_REINSTALL_VENV: '$VALUE'. Falling back to default: $FORCE_REINSTALL_VENV"
+                    fi
+                    ;;
+				FORCE_REINSTALL_DOCUMENT_ROOT)
+					if [[ "$VALUE" =~ ^[01]$ ]]; then
+                        FORCE_REINSTALL_DOCUMENT_ROOT="$VALUE"
+                        [[ "$SILENT_DISCARD" == "1" ]] && return 0 || echo "✅ Set the value for FORCE_REINSTALL_DOCUMENT_ROOT as $FORCE_REINSTALL_DOCUMENT_ROOT"
+                    else
+                        [[ "$SILENT_DISCARD" == "1" ]] && return 0 || echo "⚠️ Invalid value for FORCE_REINSTALL_DOCUMENT_ROOT: '$VALUE'. Falling back to default: $FORCE_REINSTALL_DOCUMENT_ROOT"
                     fi
                     ;;
                 TARGET_ENV)
